# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'equipmentDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Equip_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 272)
        Dialog.setStyleSheet("background-image: url(:/imgs/copy.jpg);")
        self.addattkLabel = QtWidgets.QLabel(Dialog)
        self.addattkLabel.setGeometry(QtCore.QRect(40, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.addattkLabel.setFont(font)
        self.addattkLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.addattkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addattkLabel.setObjectName("addattkLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 371, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.equipName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.equipName.setStyleSheet("color: rgb(255, 187, 0);\n"
"border-color: rgb(255, 187, 0);")
        self.equipName.setFrame(False)
        self.equipName.setAlignment(QtCore.Qt.AlignCenter)
        self.equipName.setClearButtonEnabled(False)
        self.equipName.setObjectName("equipName")
        self.verticalLayout.addWidget(self.equipName)
        self.addattkButton = QtWidgets.QPushButton(Dialog)
        self.addattkButton.setGeometry(QtCore.QRect(120, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addattkButton.setFont(font)
        self.addattkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addattkButton.setStyleSheet("color: rgb(255, 187, 0);\n"
"\n"
"background-color: rgb(97, 97, 97);")
        self.addattkButton.setCheckable(False)
        self.addattkButton.setFlat(False)
        self.addattkButton.setObjectName("addattkButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addattkLabel.setText(_translate("Dialog", "ADD EQUIPMENT"))
        self.equipName.setText(_translate("Dialog", "ENTER NAME OF ITEM"))
        self.equipName.setPlaceholderText(_translate("Dialog", "Enter Name of Attack"))
        self.addattkButton.setText(_translate("Dialog", "ADD EQUIPMENT"))
import bg_rc
