# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstpagenoequip.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 1008)
        MainWindow.setMinimumSize(QtCore.QSize(800, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(800, 1100))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 60, 60))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 50, 50))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(27, 27, 27))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.LinkVisited, brush)
        brush = QtGui.QBrush(QtGui.QColor(40, 40, 40))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-image: url(:/imgs/copy.jpg);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(20, 20, 20))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.centralwidget.setPalette(palette)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 1031))
        self.tabWidget.setMinimumSize(QtCore.QSize(451, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("border-color: rgb(255, 187, 0);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 187, 0);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.frame = QtWidgets.QFrame(self.tabWidgetPage1)
        self.frame.setGeometry(QtCore.QRect(10, 360, 191, 631))
        self.frame.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.frame.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(1)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 141, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.acrobaticsBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.acrobaticsBox.setFont(font)
        self.acrobaticsBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.acrobaticsBox.setObjectName("acrobaticsBox")
        self.verticalLayout.addWidget(self.acrobaticsBox)
        self.ahandlingBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ahandlingBox.setFont(font)
        self.ahandlingBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.ahandlingBox.setObjectName("ahandlingBox")
        self.verticalLayout.addWidget(self.ahandlingBox)
        self.arcanaBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.arcanaBox.setFont(font)
        self.arcanaBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.arcanaBox.setObjectName("arcanaBox")
        self.verticalLayout.addWidget(self.arcanaBox)
        self.athleticsBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.athleticsBox.setFont(font)
        self.athleticsBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.athleticsBox.setObjectName("athleticsBox")
        self.verticalLayout.addWidget(self.athleticsBox)
        self.deceptionBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.deceptionBox.setFont(font)
        self.deceptionBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.deceptionBox.setObjectName("deceptionBox")
        self.verticalLayout.addWidget(self.deceptionBox)
        self.historyBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.historyBox.setFont(font)
        self.historyBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.historyBox.setObjectName("historyBox")
        self.verticalLayout.addWidget(self.historyBox)
        self.insightBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.insightBox.setFont(font)
        self.insightBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.insightBox.setObjectName("insightBox")
        self.verticalLayout.addWidget(self.insightBox)
        self.intimidationBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.intimidationBox.setFont(font)
        self.intimidationBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.intimidationBox.setObjectName("intimidationBox")
        self.verticalLayout.addWidget(self.intimidationBox)
        self.investigationBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.investigationBox.setFont(font)
        self.investigationBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.investigationBox.setObjectName("investigationBox")
        self.verticalLayout.addWidget(self.investigationBox)
        self.medicinBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.medicinBox.setFont(font)
        self.medicinBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.medicinBox.setObjectName("medicinBox")
        self.verticalLayout.addWidget(self.medicinBox)
        self.natureBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.natureBox.setFont(font)
        self.natureBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.natureBox.setObjectName("natureBox")
        self.verticalLayout.addWidget(self.natureBox)
        self.perceptionBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.perceptionBox.setFont(font)
        self.perceptionBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.perceptionBox.setObjectName("perceptionBox")
        self.verticalLayout.addWidget(self.perceptionBox)
        self.performanceBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.performanceBox.setFont(font)
        self.performanceBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.performanceBox.setObjectName("performanceBox")
        self.verticalLayout.addWidget(self.performanceBox)
        self.persusasionBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.persusasionBox.setFont(font)
        self.persusasionBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.persusasionBox.setObjectName("persusasionBox")
        self.verticalLayout.addWidget(self.persusasionBox)
        self.religionBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.religionBox.setFont(font)
        self.religionBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.religionBox.setObjectName("religionBox")
        self.verticalLayout.addWidget(self.religionBox)
        self.sohBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sohBox.setFont(font)
        self.sohBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.sohBox.setObjectName("sohBox")
        self.verticalLayout.addWidget(self.sohBox)
        self.stealthBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stealthBox.setFont(font)
        self.stealthBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.stealthBox.setObjectName("stealthBox")
        self.verticalLayout.addWidget(self.stealthBox)
        self.survivalBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.survivalBox.setFont(font)
        self.survivalBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.survivalBox.setObjectName("survivalBox")
        self.verticalLayout.addWidget(self.survivalBox)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.frame)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(150, 10, 31, 611))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.acrobaticsVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.acrobaticsVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acrobaticsVal.setFont(font)
        self.acrobaticsVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.acrobaticsVal.setFrame(False)
        self.acrobaticsVal.setAlignment(QtCore.Qt.AlignCenter)
        self.acrobaticsVal.setObjectName("acrobaticsVal")
        self.verticalLayout_2.addWidget(self.acrobaticsVal)
        self.ahandlingVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.ahandlingVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ahandlingVal.setFont(font)
        self.ahandlingVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.ahandlingVal.setFrame(False)
        self.ahandlingVal.setAlignment(QtCore.Qt.AlignCenter)
        self.ahandlingVal.setObjectName("ahandlingVal")
        self.verticalLayout_2.addWidget(self.ahandlingVal)
        self.arcanaVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.arcanaVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arcanaVal.setFont(font)
        self.arcanaVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.arcanaVal.setFrame(False)
        self.arcanaVal.setAlignment(QtCore.Qt.AlignCenter)
        self.arcanaVal.setObjectName("arcanaVal")
        self.verticalLayout_2.addWidget(self.arcanaVal)
        self.athleticsVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.athleticsVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.athleticsVal.setFont(font)
        self.athleticsVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.athleticsVal.setFrame(False)
        self.athleticsVal.setAlignment(QtCore.Qt.AlignCenter)
        self.athleticsVal.setObjectName("athleticsVal")
        self.verticalLayout_2.addWidget(self.athleticsVal)
        self.deceptionVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.deceptionVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deceptionVal.setFont(font)
        self.deceptionVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.deceptionVal.setFrame(False)
        self.deceptionVal.setAlignment(QtCore.Qt.AlignCenter)
        self.deceptionVal.setObjectName("deceptionVal")
        self.verticalLayout_2.addWidget(self.deceptionVal)
        self.historyVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.historyVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.historyVal.setFont(font)
        self.historyVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.historyVal.setFrame(False)
        self.historyVal.setAlignment(QtCore.Qt.AlignCenter)
        self.historyVal.setObjectName("historyVal")
        self.verticalLayout_2.addWidget(self.historyVal)
        self.insightVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.insightVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.insightVal.setFont(font)
        self.insightVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.insightVal.setFrame(False)
        self.insightVal.setAlignment(QtCore.Qt.AlignCenter)
        self.insightVal.setObjectName("insightVal")
        self.verticalLayout_2.addWidget(self.insightVal)
        self.intimidationVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.intimidationVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.intimidationVal.setFont(font)
        self.intimidationVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.intimidationVal.setFrame(False)
        self.intimidationVal.setAlignment(QtCore.Qt.AlignCenter)
        self.intimidationVal.setObjectName("intimidationVal")
        self.verticalLayout_2.addWidget(self.intimidationVal)
        self.investigationVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.investigationVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.investigationVal.setFont(font)
        self.investigationVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.investigationVal.setFrame(False)
        self.investigationVal.setAlignment(QtCore.Qt.AlignCenter)
        self.investigationVal.setObjectName("investigationVal")
        self.verticalLayout_2.addWidget(self.investigationVal)
        self.medicineVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.medicineVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medicineVal.setFont(font)
        self.medicineVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.medicineVal.setFrame(False)
        self.medicineVal.setAlignment(QtCore.Qt.AlignCenter)
        self.medicineVal.setObjectName("medicineVal")
        self.verticalLayout_2.addWidget(self.medicineVal)
        self.natureVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.natureVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.natureVal.setFont(font)
        self.natureVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.natureVal.setFrame(False)
        self.natureVal.setAlignment(QtCore.Qt.AlignCenter)
        self.natureVal.setObjectName("natureVal")
        self.verticalLayout_2.addWidget(self.natureVal)
        self.perceptionVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.perceptionVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.perceptionVal.setFont(font)
        self.perceptionVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.perceptionVal.setFrame(False)
        self.perceptionVal.setAlignment(QtCore.Qt.AlignCenter)
        self.perceptionVal.setObjectName("perceptionVal")
        self.verticalLayout_2.addWidget(self.perceptionVal)
        self.performanceVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.performanceVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.performanceVal.setFont(font)
        self.performanceVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.performanceVal.setFrame(False)
        self.performanceVal.setAlignment(QtCore.Qt.AlignCenter)
        self.performanceVal.setObjectName("performanceVal")
        self.verticalLayout_2.addWidget(self.performanceVal)
        self.persuasionVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.persuasionVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.persuasionVal.setFont(font)
        self.persuasionVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.persuasionVal.setFrame(False)
        self.persuasionVal.setAlignment(QtCore.Qt.AlignCenter)
        self.persuasionVal.setObjectName("persuasionVal")
        self.verticalLayout_2.addWidget(self.persuasionVal)
        self.religionVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.religionVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.religionVal.setFont(font)
        self.religionVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.religionVal.setFrame(False)
        self.religionVal.setAlignment(QtCore.Qt.AlignCenter)
        self.religionVal.setObjectName("religionVal")
        self.verticalLayout_2.addWidget(self.religionVal)
        self.sohVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.sohVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sohVal.setFont(font)
        self.sohVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.sohVal.setFrame(False)
        self.sohVal.setAlignment(QtCore.Qt.AlignCenter)
        self.sohVal.setObjectName("sohVal")
        self.verticalLayout_2.addWidget(self.sohVal)
        self.stealthVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.stealthVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stealthVal.setFont(font)
        self.stealthVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.stealthVal.setFrame(False)
        self.stealthVal.setAlignment(QtCore.Qt.AlignCenter)
        self.stealthVal.setObjectName("stealthVal")
        self.verticalLayout_2.addWidget(self.stealthVal)
        self.survivalVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.survivalVal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.survivalVal.setFont(font)
        self.survivalVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.survivalVal.setFrame(False)
        self.survivalVal.setAlignment(QtCore.Qt.AlignCenter)
        self.survivalVal.setObjectName("survivalVal")
        self.verticalLayout_2.addWidget(self.survivalVal)
        self.diceBrowser = QtWidgets.QTextBrowser(self.tabWidgetPage1)
        self.diceBrowser.setGeometry(QtCore.QRect(640, 630, 141, 311))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.diceBrowser.setFont(font)
        self.diceBrowser.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.diceBrowser.setFrameShape(QtWidgets.QFrame.Box)
        self.diceBrowser.setFrameShadow(QtWidgets.QFrame.Plain)
        self.diceBrowser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.diceBrowser.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.diceBrowser.setAutoFormatting(QtWidgets.QTextEdit.AutoNone)
        self.diceBrowser.setTabChangesFocus(False)
        self.diceBrowser.setObjectName("diceBrowser")
        self.inputFrame = QtWidgets.QFrame(self.tabWidgetPage1)
        self.inputFrame.setGeometry(QtCore.QRect(640, 950, 141, 41))
        self.inputFrame.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.inputFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.inputFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.inputFrame.setObjectName("inputFrame")
        self.inputBox = QtWidgets.QLineEdit(self.inputFrame)
        self.inputBox.setGeometry(QtCore.QRect(10, 10, 121, 20))
        self.inputBox.setStyleSheet("color: rgb(255, 187, 0);")
        self.inputBox.setText("")
        self.inputBox.setFrame(False)
        self.inputBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputBox.setClearButtonEnabled(False)
        self.inputBox.setObjectName("inputBox")
        self.frame_3 = QtWidgets.QFrame(self.tabWidgetPage1)
        self.frame_3.setGeometry(QtCore.QRect(10, 150, 191, 201))
        self.frame_3.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 139, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.strBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.strBox.setFont(font)
        self.strBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.strBox.setObjectName("strBox")
        self.verticalLayout_3.addWidget(self.strBox)
        self.dexBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.dexBox.setFont(font)
        self.dexBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.dexBox.setObjectName("dexBox")
        self.verticalLayout_3.addWidget(self.dexBox)
        self.conBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.conBox.setFont(font)
        self.conBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.conBox.setObjectName("conBox")
        self.verticalLayout_3.addWidget(self.conBox)
        self.intBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.intBox.setFont(font)
        self.intBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.intBox.setObjectName("intBox")
        self.verticalLayout_3.addWidget(self.intBox)
        self.wisBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.wisBox.setFont(font)
        self.wisBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.wisBox.setObjectName("wisBox")
        self.verticalLayout_3.addWidget(self.wisBox)
        self.charBox = QtWidgets.QCheckBox(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.charBox.setFont(font)
        self.charBox.setStyleSheet("\n"
"QCheckBox::indicator {\n"
"        \n"
"    \n"
"    background-color: rgb(97, 97, 97);\n"
"}\n"
"\n"
"QCheckBox{\n"
"\n"
"color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    \n"
"    background-color: rgb(255, 187, 0);\n"
"}")
        self.charBox.setObjectName("charBox")
        self.verticalLayout_3.addWidget(self.charBox)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.frame_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(150, 10, 31, 181))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ststrLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ststrLE.setFont(font)
        self.ststrLE.setStyleSheet("color: rgb(255, 187, 0);\n"
"background: transparent;")
        self.ststrLE.setMaxLength(2)
        self.ststrLE.setFrame(False)
        self.ststrLE.setAlignment(QtCore.Qt.AlignCenter)
        self.ststrLE.setObjectName("ststrLE")
        self.verticalLayout_4.addWidget(self.ststrLE)
        self.stdexLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stdexLE.setFont(font)
        self.stdexLE.setStyleSheet("color: rgb(255, 187, 0);\n"
"background: transparent;")
        self.stdexLE.setMaxLength(2)
        self.stdexLE.setFrame(False)
        self.stdexLE.setAlignment(QtCore.Qt.AlignCenter)
        self.stdexLE.setObjectName("stdexLE")
        self.verticalLayout_4.addWidget(self.stdexLE)
        self.stconLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stconLE.setFont(font)
        self.stconLE.setStyleSheet("color: rgb(255, 187, 0);\n"
"background: transparent;")
        self.stconLE.setMaxLength(2)
        self.stconLE.setFrame(False)
        self.stconLE.setAlignment(QtCore.Qt.AlignCenter)
        self.stconLE.setObjectName("stconLE")
        self.verticalLayout_4.addWidget(self.stconLE)
        self.stintLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stintLE.setFont(font)
        self.stintLE.setStyleSheet("color: rgb(255, 187, 0);\n"
"background: transparent;")
        self.stintLE.setMaxLength(2)
        self.stintLE.setFrame(False)
        self.stintLE.setAlignment(QtCore.Qt.AlignCenter)
        self.stintLE.setObjectName("stintLE")
        self.verticalLayout_4.addWidget(self.stintLE)
        self.stwisLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stwisLE.setFont(font)
        self.stwisLE.setStyleSheet("color: rgb(255, 187, 0);\n"
"background: transparent;")
        self.stwisLE.setMaxLength(2)
        self.stwisLE.setFrame(False)
        self.stwisLE.setAlignment(QtCore.Qt.AlignCenter)
        self.stwisLE.setObjectName("stwisLE")
        self.verticalLayout_4.addWidget(self.stwisLE)
        self.stcharLE = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stcharLE.setFont(font)
        self.stcharLE.setStyleSheet("color: rgb(255, 187, 0);\n"
"background: transparent;\n"
"")
        self.stcharLE.setMaxLength(2)
        self.stcharLE.setFrame(False)
        self.stcharLE.setAlignment(QtCore.Qt.AlignCenter)
        self.stcharLE.setObjectName("stcharLE")
        self.verticalLayout_4.addWidget(self.stcharLE)
        self.savingthrowLabel = QtWidgets.QLabel(self.tabWidgetPage1)
        self.savingthrowLabel.setGeometry(QtCore.QRect(20, 120, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.savingthrowLabel.setFont(font)
        self.savingthrowLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.savingthrowLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.savingthrowLabel.setObjectName("savingthrowLabel")
        self.attributeFrame = QtWidgets.QFrame(self.tabWidgetPage1)
        self.attributeFrame.setGeometry(QtCore.QRect(10, 30, 761, 91))
        self.attributeFrame.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.attributeFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.attributeFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.attributeFrame.setObjectName("attributeFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.attributeFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 741, 53))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.strLable = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.strLable.setFont(font)
        self.strLable.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.strLable.setAlignment(QtCore.Qt.AlignCenter)
        self.strLable.setObjectName("strLable")
        self.horizontalLayout.addWidget(self.strLable)
        self.dexLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.dexLabel.setFont(font)
        self.dexLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.dexLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.dexLabel.setObjectName("dexLabel")
        self.horizontalLayout.addWidget(self.dexLabel)
        self.conLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.conLabel.setFont(font)
        self.conLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.conLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.conLabel.setObjectName("conLabel")
        self.horizontalLayout.addWidget(self.conLabel)
        self.intLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.intLabel.setFont(font)
        self.intLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.intLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.intLabel.setObjectName("intLabel")
        self.horizontalLayout.addWidget(self.intLabel)
        self.wisLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.wisLabel.setFont(font)
        self.wisLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.wisLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.wisLabel.setObjectName("wisLabel")
        self.horizontalLayout.addWidget(self.wisLabel)
        self.charLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.charLabel.setFont(font)
        self.charLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.charLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.charLabel.setObjectName("charLabel")
        self.horizontalLayout.addWidget(self.charLabel)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.attributeFrame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 741, 37))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.strVAl = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.strVAl.setFont(font)
        self.strVAl.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.strVAl.setMaxLength(2)
        self.strVAl.setFrame(False)
        self.strVAl.setAlignment(QtCore.Qt.AlignCenter)
        self.strVAl.setObjectName("strVAl")
        self.horizontalLayout_3.addWidget(self.strVAl)
        self.dexVal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.dexVal.setFont(font)
        self.dexVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.dexVal.setMaxLength(2)
        self.dexVal.setFrame(False)
        self.dexVal.setAlignment(QtCore.Qt.AlignCenter)
        self.dexVal.setObjectName("dexVal")
        self.horizontalLayout_3.addWidget(self.dexVal)
        self.conVal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.conVal.setFont(font)
        self.conVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.conVal.setMaxLength(2)
        self.conVal.setFrame(False)
        self.conVal.setAlignment(QtCore.Qt.AlignCenter)
        self.conVal.setObjectName("conVal")
        self.horizontalLayout_3.addWidget(self.conVal)
        self.intVal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.intVal.setFont(font)
        self.intVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.intVal.setMaxLength(2)
        self.intVal.setFrame(False)
        self.intVal.setAlignment(QtCore.Qt.AlignCenter)
        self.intVal.setObjectName("intVal")
        self.horizontalLayout_3.addWidget(self.intVal)
        self.wisVal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.wisVal.setFont(font)
        self.wisVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.wisVal.setMaxLength(2)
        self.wisVal.setFrame(False)
        self.wisVal.setAlignment(QtCore.Qt.AlignCenter)
        self.wisVal.setObjectName("wisVal")
        self.horizontalLayout_3.addWidget(self.wisVal)
        self.charVal = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.charVal.setFont(font)
        self.charVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.charVal.setMaxLength(2)
        self.charVal.setFrame(False)
        self.charVal.setAlignment(QtCore.Qt.AlignCenter)
        self.charVal.setObjectName("charVal")
        self.horizontalLayout_3.addWidget(self.charVal)
        self.frame_4 = QtWidgets.QFrame(self.tabWidgetPage1)
        self.frame_4.setGeometry(QtCore.QRect(640, 150, 141, 191))
        self.frame_4.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(98, 10, 31, 171))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.acVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.acVal.setFont(font)
        self.acVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.acVal.setMaxLength(3)
        self.acVal.setFrame(False)
        self.acVal.setAlignment(QtCore.Qt.AlignCenter)
        self.acVal.setObjectName("acVal")
        self.verticalLayout_7.addWidget(self.acVal)
        self.spdVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spdVal.setFont(font)
        self.spdVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.spdVal.setMaxLength(3)
        self.spdVal.setFrame(False)
        self.spdVal.setCursorPosition(1)
        self.spdVal.setAlignment(QtCore.Qt.AlignCenter)
        self.spdVal.setObjectName("spdVal")
        self.verticalLayout_7.addWidget(self.spdVal)
        self.hpVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hpVal.setFont(font)
        self.hpVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.hpVal.setMaxLength(3)
        self.hpVal.setFrame(False)
        self.hpVal.setAlignment(QtCore.Qt.AlignCenter)
        self.hpVal.setObjectName("hpVal")
        self.verticalLayout_7.addWidget(self.hpVal)
        self.temphpVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temphpVal.setFont(font)
        self.temphpVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.temphpVal.setMaxLength(3)
        self.temphpVal.setFrame(False)
        self.temphpVal.setAlignment(QtCore.Qt.AlignCenter)
        self.temphpVal.setObjectName("temphpVal")
        self.verticalLayout_7.addWidget(self.temphpVal)
        self.profecVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.profecVal.setFont(font)
        self.profecVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.profecVal.setMaxLength(3)
        self.profecVal.setFrame(False)
        self.profecVal.setCursorPosition(1)
        self.profecVal.setAlignment(QtCore.Qt.AlignCenter)
        self.profecVal.setObjectName("profecVal")
        self.verticalLayout_7.addWidget(self.profecVal)
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.frame_4)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 91, 171))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.acLabel = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acLabel.sizePolicy().hasHeightForWidth())
        self.acLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.acLabel.setFont(font)
        self.acLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.acLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.acLabel.setObjectName("acLabel")
        self.verticalLayout_8.addWidget(self.acLabel)
        self.spdLabel = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spdLabel.sizePolicy().hasHeightForWidth())
        self.spdLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.spdLabel.setFont(font)
        self.spdLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.spdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.spdLabel.setObjectName("spdLabel")
        self.verticalLayout_8.addWidget(self.spdLabel)
        self.hpLabel = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hpLabel.sizePolicy().hasHeightForWidth())
        self.hpLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.hpLabel.setFont(font)
        self.hpLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.hpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.hpLabel.setObjectName("hpLabel")
        self.verticalLayout_8.addWidget(self.hpLabel)
        self.temphpLabel = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temphpLabel.sizePolicy().hasHeightForWidth())
        self.temphpLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.temphpLabel.setFont(font)
        self.temphpLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.temphpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.temphpLabel.setObjectName("temphpLabel")
        self.verticalLayout_8.addWidget(self.temphpLabel)
        self.profecLabel = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.profecLabel.sizePolicy().hasHeightForWidth())
        self.profecLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.profecLabel.setFont(font)
        self.profecLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.profecLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.profecLabel.setObjectName("profecLabel")
        self.verticalLayout_8.addWidget(self.profecLabel)
        self.profEdit = QtWidgets.QTextEdit(self.tabWidgetPage1)
        self.profEdit.setGeometry(QtCore.QRect(640, 350, 141, 271))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.profEdit.setFont(font)
        self.profEdit.setStyleSheet("border-color: rgb(255, 187, 0);\n"
"selection-color: rgb(255, 187, 0);")
        self.profEdit.setObjectName("profEdit")
        self.attackFrame = QtWidgets.QFrame(self.tabWidgetPage1)
        self.attackFrame.setGeometry(QtCore.QRect(210, 150, 421, 271))
        self.attackFrame.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.attackFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.attackFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.attackFrame.setObjectName("attackFrame")
        self.attackView = QtWidgets.QTableWidget(self.attackFrame)
        self.attackView.setGeometry(QtCore.QRect(5, 11, 411, 251))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 135, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.attackView.setPalette(palette)
        self.attackView.setStyleSheet("\n"
"background:transparent;\n"
"")
        self.attackView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.attackView.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.attackView.setShowGrid(True)
        self.attackView.setRowCount(0)
        self.attackView.setColumnCount(3)
        self.attackView.setObjectName("attackView")
        self.attackView.horizontalHeader().setVisible(False)
        self.attackView.horizontalHeader().setCascadingSectionResizes(True)
        self.attackView.horizontalHeader().setDefaultSectionSize(137)
        self.attackView.horizontalHeader().setHighlightSections(False)
        self.attackView.horizontalHeader().setMinimumSectionSize(100)
        self.attackView.horizontalHeader().setStretchLastSection(False)
        self.attackView.verticalHeader().setVisible(False)
        self.attackView.verticalHeader().setCascadingSectionResizes(True)
        self.attackView.verticalHeader().setHighlightSections(False)
        self.attackView.verticalHeader().setStretchLastSection(False)
        self.frame_16 = QtWidgets.QFrame(self.tabWidgetPage1)
        self.frame_16.setGeometry(QtCore.QRect(210, 830, 421, 161))
        self.frame_16.setStyleSheet("QFrame { \n"
"    color: rgb(184, 135, 0);\n"
"} ")
        self.frame_16.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.layoutWidget = QtWidgets.QWidget(self.frame_16)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 121, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.nameLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.nameLabel.setFont(font)
        self.nameLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.nameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.verticalLayout_22.addWidget(self.nameLabel)
        self.raceLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.raceLabel.setFont(font)
        self.raceLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.raceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.raceLabel.setObjectName("raceLabel")
        self.verticalLayout_22.addWidget(self.raceLabel)
        self.classLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.classLabel.setFont(font)
        self.classLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.classLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.classLabel.setObjectName("classLabel")
        self.verticalLayout_22.addWidget(self.classLabel)
        self.expLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.expLabel.setFont(font)
        self.expLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.expLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.expLabel.setObjectName("expLabel")
        self.verticalLayout_22.addWidget(self.expLabel)
        self.levelLabel = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.levelLabel.sizePolicy().hasHeightForWidth())
        self.levelLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.levelLabel.setFont(font)
        self.levelLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.levelLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.levelLabel.setObjectName("levelLabel")
        self.verticalLayout_22.addWidget(self.levelLabel)
        self.nameLabel.raise_()
        self.raceLabel.raise_()
        self.expLabel.raise_()
        self.levelLabel.raise_()
        self.classLabel.raise_()
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.frame_16)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(150, 10, 261, 141))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.nameVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameVal.setFont(font)
        self.nameVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.nameVal.setMaxLength(1000)
        self.nameVal.setFrame(False)
        self.nameVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.nameVal.setObjectName("nameVal")
        self.verticalLayout_20.addWidget(self.nameVal)
        self.raceVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.raceVal.setFont(font)
        self.raceVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.raceVal.setMaxLength(1000)
        self.raceVal.setFrame(False)
        self.raceVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.raceVal.setObjectName("raceVal")
        self.verticalLayout_20.addWidget(self.raceVal)
        self.classVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.classVal.setFont(font)
        self.classVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.classVal.setMaxLength(1000)
        self.classVal.setFrame(False)
        self.classVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.classVal.setObjectName("classVal")
        self.verticalLayout_20.addWidget(self.classVal)
        self.expVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.expVal.setFont(font)
        self.expVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.expVal.setMaxLength(1000)
        self.expVal.setFrame(False)
        self.expVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.expVal.setObjectName("expVal")
        self.verticalLayout_20.addWidget(self.expVal)
        self.levelVal = QtWidgets.QLineEdit(self.verticalLayoutWidget_20)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.levelVal.setFont(font)
        self.levelVal.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.levelVal.setMaxLength(1000)
        self.levelVal.setFrame(False)
        self.levelVal.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.levelVal.setObjectName("levelVal")
        self.verticalLayout_20.addWidget(self.levelVal)
        self.attkButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.attkButton.setGeometry(QtCore.QRect(340, 120, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.attkButton.setFont(font)
        self.attkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.attkButton.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.attkButton.setObjectName("attkButton")
        self.euipButton = QtWidgets.QPushButton(self.tabWidgetPage1)
        self.euipButton.setGeometry(QtCore.QRect(340, 420, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.euipButton.setFont(font)
        self.euipButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.euipButton.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.euipButton.setObjectName("euipButton")
        self.equipEdit = QtWidgets.QTextEdit(self.tabWidgetPage1)
        self.equipEdit.setGeometry(QtCore.QRect(210, 450, 421, 361))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.equipEdit.setFont(font)
        self.equipEdit.setStyleSheet("border-color: rgb(255, 187, 0);\n"
"selection-color: rgb(255, 187, 0);")
        self.equipEdit.setObjectName("equipEdit")
        self.frame_16.raise_()
        self.equipEdit.raise_()
        self.frame.raise_()
        self.diceBrowser.raise_()
        self.inputFrame.raise_()
        self.frame_3.raise_()
        self.savingthrowLabel.raise_()
        self.attributeFrame.raise_()
        self.frame_4.raise_()
        self.profEdit.raise_()
        self.attackFrame.raise_()
        self.attkButton.raise_()
        self.euipButton.raise_()
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.spellLabel = QtWidgets.QLabel(self.tabWidgetPage2)
        self.spellLabel.setGeometry(QtCore.QRect(340, 0, 118, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.spellLabel.setFont(font)
        self.spellLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;\n"
"border-color: rgb(255, 187, 0);")
        self.spellLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.spellLabel.setObjectName("spellLabel")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 80, 781, 261))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cantripView = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 187, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.cantripView.setPalette(palette)
        self.cantripView.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.cantripView.setStyleSheet("background-color: rgb(255, 187, 0);\n"
"")
        self.cantripView.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.cantripView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.cantripView.setItemAlignment(QtCore.Qt.AlignCenter)
        self.cantripView.setObjectName("cantripView")
        self.horizontalLayout_2.addWidget(self.cantripView)
        self.lv1View = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.lv1View.setStyleSheet("border-color: rgb(255, 187, 0);")
        self.lv1View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv1View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv1View.setObjectName("lv1View")
        self.horizontalLayout_2.addWidget(self.lv1View)
        self.lv2View = QtWidgets.QListWidget(self.horizontalLayoutWidget_3)
        self.lv2View.setStyleSheet("")
        self.lv2View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv2View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv2View.setObjectName("lv2View")
        self.horizontalLayout_2.addWidget(self.lv2View)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 390, 781, 261))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lv3View = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.lv3View.setStyleSheet("")
        self.lv3View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv3View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv3View.setObjectName("lv3View")
        self.horizontalLayout_4.addWidget(self.lv3View)
        self.lv4View = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.lv4View.setStyleSheet("")
        self.lv4View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv4View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv4View.setObjectName("lv4View")
        self.horizontalLayout_4.addWidget(self.lv4View)
        self.lv5View = QtWidgets.QListWidget(self.horizontalLayoutWidget_4)
        self.lv5View.setStyleSheet("")
        self.lv5View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv5View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv5View.setObjectName("lv5View")
        self.horizontalLayout_4.addWidget(self.lv5View)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tabWidgetPage2)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 700, 781, 261))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lv6View = QtWidgets.QListWidget(self.horizontalLayoutWidget_5)
        self.lv6View.setStyleSheet("")
        self.lv6View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv6View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv6View.setObjectName("lv6View")
        self.horizontalLayout_5.addWidget(self.lv6View)
        self.lv7View = QtWidgets.QListWidget(self.horizontalLayoutWidget_5)
        self.lv7View.setStyleSheet("")
        self.lv7View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv7View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv7View.setObjectName("lv7View")
        self.horizontalLayout_5.addWidget(self.lv7View)
        self.lv8View = QtWidgets.QListWidget(self.horizontalLayoutWidget_5)
        self.lv8View.setStyleSheet("")
        self.lv8View.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lv8View.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lv8View.setObjectName("lv8View")
        self.horizontalLayout_5.addWidget(self.lv8View)
        self.spellButton = QtWidgets.QPushButton(self.tabWidgetPage2)
        self.spellButton.setGeometry(QtCore.QRect(330, 50, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.spellButton.setFont(font)
        self.spellButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.spellButton.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.spellButton.setObjectName("spellButton")
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.characterEdit = QtWidgets.QTextEdit(self.tab)
        self.characterEdit.setGeometry(QtCore.QRect(10, 20, 781, 961))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.characterEdit.setFont(font)
        self.characterEdit.setObjectName("characterEdit")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SweetCharacterSheet"))
        self.acrobaticsBox.setText(_translate("MainWindow", "Acrobatics"))
        self.ahandlingBox.setText(_translate("MainWindow", "A-HANDLING"))
        self.arcanaBox.setText(_translate("MainWindow", "Arcana"))
        self.athleticsBox.setText(_translate("MainWindow", "Athletics"))
        self.deceptionBox.setText(_translate("MainWindow", "Deception"))
        self.historyBox.setText(_translate("MainWindow", "History"))
        self.insightBox.setText(_translate("MainWindow", "Insight"))
        self.intimidationBox.setText(_translate("MainWindow", "Intimidation"))
        self.investigationBox.setText(_translate("MainWindow", "Investigation"))
        self.medicinBox.setText(_translate("MainWindow", "Medicine"))
        self.natureBox.setText(_translate("MainWindow", "Nature"))
        self.perceptionBox.setText(_translate("MainWindow", "Perception"))
        self.performanceBox.setText(_translate("MainWindow", "Performance"))
        self.persusasionBox.setText(_translate("MainWindow", "Persuasion"))
        self.religionBox.setText(_translate("MainWindow", "Religion"))
        self.sohBox.setText(_translate("MainWindow", "SOH"))
        self.stealthBox.setText(_translate("MainWindow", "Stealth"))
        self.survivalBox.setText(_translate("MainWindow", "Survival"))
        self.acrobaticsVal.setText(_translate("MainWindow", "0"))
        self.ahandlingVal.setText(_translate("MainWindow", "0"))
        self.arcanaVal.setText(_translate("MainWindow", "0"))
        self.athleticsVal.setText(_translate("MainWindow", "0"))
        self.deceptionVal.setText(_translate("MainWindow", "0"))
        self.historyVal.setText(_translate("MainWindow", "0"))
        self.insightVal.setText(_translate("MainWindow", "0"))
        self.intimidationVal.setText(_translate("MainWindow", "0"))
        self.investigationVal.setText(_translate("MainWindow", "0"))
        self.medicineVal.setText(_translate("MainWindow", "0"))
        self.natureVal.setText(_translate("MainWindow", "0"))
        self.perceptionVal.setText(_translate("MainWindow", "0"))
        self.performanceVal.setText(_translate("MainWindow", "0"))
        self.persuasionVal.setText(_translate("MainWindow", "0"))
        self.religionVal.setText(_translate("MainWindow", "0"))
        self.sohVal.setText(_translate("MainWindow", "0"))
        self.stealthVal.setText(_translate("MainWindow", "0"))
        self.survivalVal.setText(_translate("MainWindow", "0"))
        self.inputBox.setPlaceholderText(_translate("MainWindow", "Enter Command"))
        self.strBox.setText(_translate("MainWindow", "STR"))
        self.dexBox.setText(_translate("MainWindow", "DEX"))
        self.conBox.setText(_translate("MainWindow", "CON"))
        self.intBox.setText(_translate("MainWindow", "INT"))
        self.wisBox.setText(_translate("MainWindow", "WIS"))
        self.charBox.setText(_translate("MainWindow", "CHR"))
        self.ststrLE.setText(_translate("MainWindow", "0"))
        self.stdexLE.setText(_translate("MainWindow", "0"))
        self.stconLE.setText(_translate("MainWindow", "0"))
        self.stintLE.setText(_translate("MainWindow", "0"))
        self.stwisLE.setText(_translate("MainWindow", "0"))
        self.stcharLE.setText(_translate("MainWindow", "0"))
        self.savingthrowLabel.setText(_translate("MainWindow", "SAVING THROWS"))
        self.strLable.setText(_translate("MainWindow", "STR"))
        self.dexLabel.setText(_translate("MainWindow", "DEX"))
        self.conLabel.setText(_translate("MainWindow", "CON"))
        self.intLabel.setText(_translate("MainWindow", "INT"))
        self.wisLabel.setText(_translate("MainWindow", "WIS"))
        self.charLabel.setText(_translate("MainWindow", "CHR"))
        self.strVAl.setText(_translate("MainWindow", "0"))
        self.dexVal.setText(_translate("MainWindow", "0"))
        self.conVal.setText(_translate("MainWindow", "0"))
        self.intVal.setText(_translate("MainWindow", "0"))
        self.wisVal.setText(_translate("MainWindow", "0"))
        self.charVal.setText(_translate("MainWindow", "0"))
        self.acVal.setText(_translate("MainWindow", "0"))
        self.spdVal.setText(_translate("MainWindow", "0"))
        self.hpVal.setText(_translate("MainWindow", "0"))
        self.temphpVal.setText(_translate("MainWindow", "0"))
        self.profecVal.setText(_translate("MainWindow", "0"))
        self.acLabel.setText(_translate("MainWindow", "AC"))
        self.spdLabel.setText(_translate("MainWindow", "SPD"))
        self.hpLabel.setText(_translate("MainWindow", "HP"))
        self.temphpLabel.setText(_translate("MainWindow", "TEMP HP"))
        self.profecLabel.setText(_translate("MainWindow", "PROF"))
        self.profEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt; font-weight:600; text-decoration: underline; color:#ffbb00;\">Other Profeciences</span></p>\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt; font-weight:600; text-decoration: underline; color:#ffbb00;\"><br /></p></body></html>"))
        self.nameLabel.setText(_translate("MainWindow", "PLAYER NAME"))
        self.raceLabel.setText(_translate("MainWindow", "RACE"))
        self.classLabel.setText(_translate("MainWindow", "CLASS"))
        self.expLabel.setText(_translate("MainWindow", "EXP"))
        self.levelLabel.setText(_translate("MainWindow", "LEVEL"))
        self.nameVal.setText(_translate("MainWindow", "INSERT NAME"))
        self.raceVal.setText(_translate("MainWindow", "INSERT RACE"))
        self.classVal.setText(_translate("MainWindow", "INSERT CLASS"))
        self.expVal.setText(_translate("MainWindow", "INSERT EXP"))
        self.levelVal.setText(_translate("MainWindow", "INSERT LEVEL"))
        self.attkButton.setText(_translate("MainWindow", "ADD ATTACK"))
        self.euipButton.setText(_translate("MainWindow", "ADD EQUIPMENT"))
        self.equipEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("MainWindow", "Main"))
        self.spellLabel.setText(_translate("MainWindow", "SPELLS"))
        self.cantripView.setSortingEnabled(True)
        self.spellButton.setText(_translate("MainWindow", "ADD SPELL"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("MainWindow", "Spells"))
        self.characterEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Character Info"))
import bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
