# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attackDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Attack_Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 272)
        Dialog.setStyleSheet("background-image: url(:/imgs/copy.jpg);")
        self.addattkLabel = QtWidgets.QLabel(Dialog)
        self.addattkLabel.setGeometry(QtCore.QRect(40, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.addattkLabel.setFont(font)
        self.addattkLabel.setStyleSheet("color: rgb(255, 187, 0);\n"
"background:transparent;")
        self.addattkLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.addattkLabel.setObjectName("addattkLabel")
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 60, 371, 131))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.attkName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.attkName.setStyleSheet("color: rgb(255, 187, 0);\n"
"border-color: rgb(255, 187, 0);")
        self.attkName.setFrame(False)
        self.attkName.setAlignment(QtCore.Qt.AlignCenter)
        self.attkName.setClearButtonEnabled(False)
        self.attkName.setObjectName("attkName")
        self.verticalLayout.addWidget(self.attkName)
        self.attkRTH = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.attkRTH.setStyleSheet("color: rgb(255, 187, 0);\n"
"border-color: rgb(255, 187, 0);")
        self.attkRTH.setFrame(False)
        self.attkRTH.setAlignment(QtCore.Qt.AlignCenter)
        self.attkRTH.setClearButtonEnabled(False)
        self.attkRTH.setObjectName("attkRTH")
        self.verticalLayout.addWidget(self.attkRTH)
        self.attkDR = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.attkDR.setStyleSheet("color: rgb(255, 187, 0);\n"
"border-color: rgb(255, 187, 0);")
        self.attkDR.setFrame(False)
        self.attkDR.setAlignment(QtCore.Qt.AlignCenter)
        self.attkDR.setClearButtonEnabled(False)
        self.attkDR.setObjectName("attkDR")
        self.verticalLayout.addWidget(self.attkDR)
        self.addattkButton = QtWidgets.QPushButton(Dialog)
        self.addattkButton.setGeometry(QtCore.QRect(120, 220, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.addattkButton.setFont(font)
        self.addattkButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addattkButton.setStyleSheet("color: rgb(255, 187, 0);\n"
"\n"
"background-color: rgb(97, 97, 97);")
        self.addattkButton.setCheckable(False)
        self.addattkButton.setFlat(False)
        self.addattkButton.setObjectName("addattkButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addattkLabel.setText(_translate("Dialog", "ADD ATTACK"))
        self.attkName.setText(_translate("Dialog", "ENTER NAME OF ATTACK"))
        self.attkName.setPlaceholderText(_translate("Dialog", "Enter Name of Attack"))
        self.attkRTH.setText(_translate("Dialog", "ENTER ROLL TO HIT EX: 1d20 + 4"))
        self.attkRTH.setPlaceholderText(_translate("Dialog", "ENTER DICE ROLL EX: 1d20 + 4"))
        self.attkDR.setText(_translate("Dialog", "ENTER ATTACK ROLL EX: 1d20 + 4"))
        self.attkDR.setPlaceholderText(_translate("Dialog", "ENTER DICE ROLL EX: 1d20 + 4"))
        self.addattkButton.setText(_translate("Dialog", "ADD ATTACK"))
import bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
